### ISSUE TITLE
highlight not working 

### ISSUE THREAD

**Issue by kunalkumar007** [jpuri/react-draft-wysiwyg#1167]
Here is the whole issue I am having [Stack overflow link](https://stackoverflow.com/questions/68771038/highlight-functionality-in-draft-editor-not-working).
After implementing Highlight using a style map. My code is not getting highlighted.

**Comment by Eireinei** [comment]
Hey, this is not a bug, #fdaed27 is not a valid color. Try for example with #8e9fbd it should work. For info, this package is no longer maintained by the author, it is dying. I strongly recommend that you use another package :)

**Comment by kunalkumar007** [comment]
Thanķs for the help. I diďt knew about it.

**Comment by Eireinei** [comment]
dd

**Comment by Eireinei** [comment]
Yes it is not specified on the main page, but if we look we can see a lot of known bugs which are not fixed with multiple commits and pull request pending for a very long time. You can watch this discussion to learn more https://github.com/jpuri/react-draft-wysiwyg/issues/879

The author prefers to focus on http://www.nibedit.com.

If you prefer draft.js over prosemirror and are comfortable with hooks, you can check out this library at https://github.com/romainleduc/draft-js-rte. It's only at the beginning but you can watch it, it's really cool but requires a little more code :)
An example of your result with this library
https://codesandbox.io/s/highlight-inline-style-9qiob

**Comment by kunalkumar007** [comment]
As it is mentioned that the package is no longer maintained. I am satisfied with another Package. Thanks for the Help.
