### ISSUE TITLE
convertFromHTML example does not work with <img>

### ISSUE THREAD

**Issue by yamat124** [jpuri/react-draft-wysiwyg#174]
I'm trying to re-create my EditorState just like the example in the demo. the raw string from my server looks like this: 
const text = "<p></p>\r\n<img src=\"http://i.imgur.com/x60JSwk.jpg\" style=\"height: auto; width: 100%;\"/>\r\n<p></p>\r\n"

const blocksFromHTML = convertFromHTML(text);
            const newState = ContentState.createFromBlockArray(
                blocksFromHTML.contentBlocks
            );

let rawState = EditorState.createWithContent(newState, this.state.decorator)
<Editor
                    defaultEditorState={rawState}
                    toolbarClassName="demo-toolbar"
                    editorClassName="demo-editor"
                    wrapperClassName="demo-wrapper-wide"
                    onEditorStateChange={this.onEditorStateChange.bind(this, 0)}
                />
Images wont render and links in the text wont render the editor. I see this is problem with draft-js 0.9.1 which was probable fixed in draft-js 0.10.x.

Can you help. Thanks.

**Comment by jpuri** [comment]
Hey @yamat124:

For html generated the the editor you can try out library `https://github.com/jpuri/html-to-draftjs`.
The method provided by draftjs supports only a limited set of tags.

**Comment by yamat124** [comment]
Thanks I will test it and let you know.

**Comment by jpuri** [comment]
Closing as there is no response, if required it can be re-opened.

**Comment by MilanRgm** [comment]
I am in the same boat. Hello, 

Why my editor does not show image when all the html elements are parsed to plain text? I get content in html from api which i need to show in markup. Everything is shown perfectly except the image part. I mean `<img src="http://image_url" />` is shown the url like http://image_url instead of image.

Here is my code 

```javascript
const decorator = new CompositeDecorator([
  {
    strategy: findImageEntities,
    component: Image
  }
]);

function findImageEntities(contentBlock, callback, contentState) {
  contentBlock.findEntityRanges(character => {
    const entityKey = character.getEntity();
    return (
      entityKey !== null &&
      contentState.getEntity(entityKey).getType() === "IMAGE"
    );
  }, callback);
}

const Image = props => {
  const { height, src, width } = props.contentState
    .getEntity(props.entityKey)
    .getData();
  return <img src={src} height={height} width={width} />;
};

class AdminEditor extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      editorState: EditorState.createEmpty(),
      editorContent: undefined,
      contentState: "",
      touched: false
    };
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.htmlMarkup !== this.props.htmlMarkup) {
      const content = nextProps.htmlMarkup;
      const blocksFromHTML = convertFromHTML(content);
      const plainState = ContentState.createFromBlockArray(
        blocksFromHTML.contentBlocks,
        blocksFromHTML.entityMap
      );
      this.setState(state => ({
        editorState: EditorState.createWithContent(plainState, decorator)
      }));
    }
  }

  imageUploadCallBack = file =>
    new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest(); // eslint-disable-line no-undef
      xhr.open("POST", "https://api.imgur.com/3/image");
      xhr.setRequestHeader("Authorization", "Client-ID 8d26ccd12712fca");
      const data = new FormData(); // eslint-disable-line no-undef
      data.append("image", file);
      xhr.send(data);
      xhr.addEventListener("load", () => {
        const response = JSON.parse(xhr.responseText);
        resolve(response);
      });
      xhr.addEventListener("error", () => {
        const error = JSON.parse(xhr.responseText);
        reject(error);
      });
    });

  onEditorStateChange = editorState => {
    this.setState({
      editorState
    });
  };

  onEditorChange = editorContent => {
    this.setState({
      editorContent
    });
  };

  render() {
    const { editorState } = this.state;
    const { stateOfEditor } = this.props;
    return (
      <div>
        <Editor
          tabIndex={0}
          editorState={editorState}
          initialContentState={this.props.htmlMarkup}
          onEditorStateChange={this.onEditorStateChange}
          decorators={decorator}
          toolbar={{
            inline: { inDropdown: false },
            link: { showOpenOptionOnHover: true },
            textAlign: { inDropdown: true },
            image: {
              uploadCallback: this.imageUploadCallBack,
              defaultSize: { height: "auto", width: "50%" }
            }
          }}
          onContentStateChange={this.onEditorChange}
          onChange={this.handleChange}
          onBlur={this.handleBlur}
        />
      </div>
    );
  }
}

export default AdminEditor;
```

I have used the decorator either but still image is not shown.

**Comment by kohgpat** [comment]
@MilanRgm Hi. I have this issue couple of days ago. The issue here is that you're using decorator example from draft-js documentation and applying it that way. As I found out react-draft-wysiwyg have a special customDecorators prop to pass decorators to draft-js Editor. Use your decorators that way and the editor would apply the decorators, and you'll have your images created using your Image component. But there is another issue because react-draft-wysiwyg use it's own solution for images you wouldn't be able to use image alignment options for example. So the right way here is to use htmlToDraft function from https://github.com/jpuri/html-to-draftjs instead of convertFromHTML for images compatible with react-draft-wysiwyg editor without custom decorators and image components.
