### ISSUE TITLE
uploadCallback error handling 

### ISSUE THREAD

**Issue by CallMeXYZ** [jpuri/react-draft-wysiwyg#252]
could you supply a demo error handling inside uploadCallback? now, either `reject(error)` or `throw` inside the promise returned can cancle the loading state.
now i just uglily return false to cancel loading when error  happens
```javascript
const uploadCallback = (file) => {
    const form = new FormData();
    form.append('photo', file);
    return Post(URL_UPLOAD, form).then(({result, error}) => {
        if(error) {
            message.error(error);
           return false;
        }
        return new Promise((resolve) => {
                resolve({data: {link: result.url}});
        });

    });
};
```

**Comment by lavoiedn** [comment]
My team and I were wondering the same thing about the best practice for handling upload errors. We found a solution but if I remember correctly it still fails in the `then` call when the image is uploaded because of the missing rejection handler. Perhaps the solution would be to allow an optional error handling callback (something like`uploadErrorCallback`) to be passed with the options for the image tool?

Here is what we did:

```js
const uploadCallback = (file) => {
    return new Promise(
      (resolve, reject) => {
        this.uploadImage(file, (err, url) => {
          if (err) {
            reject(err.toString());
          } else {
            resolve({ data: { link: url } });
          }
        });
      }
    ).catch(err => {
      // TODO: Handle error display in the form here
      return err;
    });
  }
```

I'd love to see how others have done it to see if there's a better way to handle the rejection without running into the error: 

> Unhandled promise rejection TypeError: t is undefined

Seems like there's already a suggested change to upload error handling #254

**Comment by gablabelle** [comment]
@lavoiedn yes in fact we also did almost the same change he did in the fork https://github.com/Amitom/react-draft-wysiwyg/commit/46ea06b800e7ec844d5d17493551cea025eb8136

**Comment by CallMeXYZ** [comment]
@lavoiedn it seems that your method cannot cancel loading state either.Haven't thought that the error was not caught,hah

**Comment by lavoiedn** [comment]
@CallMeXYZ Yeah you are right, I realized that we had to make other changes to get it to work as @gablabelle says. The fix @the1sky suggested in #254 would probably fix all those issues since it resets the image upload widget's state.

However, if I'm not mistaken, that implementation will not propagate the error, preventing users from displaying the error the way they want to.

I'm not an expert on Promises, but perhaps something like the code below would work.

```js
uploadImage: Function = (file: Object): void => {
  this.toggleShowImageLoading();
  const { uploadCallback } = this.props.config;
  uploadCallback(file)
    .then(({ data }) => {
      this.setState({
        showImageLoading: false,
        dragEnter: false,
      });
      this.addImageFromSrcLink(data.link);
    }).catch((e) => {
      this.setState({
        showImageLoading: false,
        dragEnter: false,
      });
      return new Promise.reject(e);
    });
};
```

**Comment by CallMeXYZ** [comment]
@lavoiedn I think we dont have to.Who will catch the `reject`  and who you want the error be propagated to? It's a resonable procedure that user handle their own Api request,return propriate values to the editor and the editor manage the state by the values.

**Comment by jpuri** [comment]
Agree with @CallMeXYZ

**Comment by the1sky** [comment]
@CallMeXYZ , as you say, image upload state always be set with:

`this.setState({
        showImageLoading: false,
        dragEnter: false,
      });`

but editor always insert an empty image

**Comment by jpuri** [comment]
@the1sky: I think it would be nice fix to add image only if non-null value is returned. Plz suggest.

**Comment by CallMeXYZ** [comment]
@the1sky didn't get you.What i'm saying is  to explain why we don't need propagate the error inside the root editor.
I mean users may supply `uploadCallback ` like below
```javascript
const uploadCallback = (file) => {
    const form = new FormData();
    form.append('photo', file);
    //user handle their own request error
    const {result, error} = Api(form);
    return new Promise((resolve, reject) => {
        if (error) reject(error);
        else  resolve({data: {link: result.url}});
    });
};
```
then the editor manager itself by the resolved data (show img,cancel loading) or the rejected error (cancel loading,maybe show error in debug mode) .
As @jpuri  said, we'd better validatethe data  even if the user resolve a data.

**Comment by the1sky** [comment]
@CallMeXYZ yeah, should validate the data, and clear error in debug mode

**Comment by jpuri** [comment]
Upload call-back now takes care of error scenarios: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/components/Controls/Image/Component/index.js#L118
