### ISSUE TITLE
Question: Why `react-draft-wysiwyg`?

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [jpuri/react-draft-wysiwyg#580]
Hello all,

Just picked up this editor without any reasoning, but could you tell me what the difference between this and just [Draft-JS](https://github.com/facebook/draft-js)?

**Comment by lefnire** [comment]
Draft is a framework: tools to build your own WYSIWYG from scratch. But you'll be writing a helluva lotta code if you want more than just a bold and italic button. This uses Draft to build a full fledged WYSIWYG users can use outa the box. Because it's so all-encompassing, and basically one maintainer, there are lots of bugs. Do you need a lot of WYSIWYG functionality? (Bold, italic, codeblock, blockquote, lists, images, upload, links, ...) Use this project. Just a few small things? Build it yourself with Draft.

**Comment by AlexanderTserkovniy** [comment]
@lefnire thanks a lot, clear. Will try to help you when I have time.

**Comment by lefnire** [comment]
@AlexanderTserkovniy oh I'm not the maintainer, it's @jpuri. Poor lady must feel buried, so I'm sure she'll appreciate the help :)
